const axios = require('axios');

// แปลงข้อมูลใบขายจาก ERP เป็น payload สำหรับ e-tax
exports.transformInvoice = (invoice) => {
  // ตัวอย่าง mapping แบบง่าย (ควรปรับให้ตรงกับ spec จริง)
  return {
    SellerTaxId: "0105565034824",
    SellerBranchId: "00000",
    APIKey: process.env.ETAX_API_KEY || "",
    UserCode: process.env.ETAX_USER_CODE || "",
    AccessKey: process.env.ETAX_ACCESS_KEY || "",
    ServiceCode: "S03",
    TextContent: {
      "C01-SELLER_TAX_ID": "0105565034824",
      "C02-SELLER_BRANCH_ID": "00000",
      "C03-FILE_NAME": `${invoice.SALES_INVOICE_NO}.txt`,
      "H01-DOCUMENT_TYPE_CODE": "T01",
      "H02-DOCUMENT_NAME": "ใบเสร็จรับเงิน",
      "H03-DOCUMENT_ID": String(invoice.SALES_INVOICE_NO),
      "H04-DOCUMENT_ISSUE_DTM": String(invoice.SALES_INVOICE_DATE),
      "H05-CREATE_PURPOSE_CODE": "",
      "H06-CREATE_PURPOSE": "",
      "H07-ADDITIONAL_REF_ASSIGN_ID": "",
      "H08-ADDITIONAL_REF_ISSUE_DTM": "",
      "H09-ADDITIONAL_REF_TYPE_CODE": "",
      "H10-ADDITIONAL_REF_DOCUMENT_NAME": "",
      "H11-DELIVERY_TYPE_CODE": "",
      "H12-BUYER_ORDER_ASSIGN_ID": "",
      "H13-BUYER_ORDER_ISSUE_DTM": "",
      "H14-BUYER_ORDER_REF_TYPE_CODE": "",
      "H15-DOCUMENT_REMARK": "",
      "H16-VOUCHER_NO": "",
      "H17-SELLER_CONTACT_PERSON_NAME": "",
      "H18-SELLER_CONTACT_DEPARTMENT_NAME": "",
      "H19-SELLER_CONTACT_URIID": "",
      "H20-SELLER_CONTACT_PHONE_NO": "",
      "H21-FLEX_FIELD": "",
      "H22-SELLER_BRANCH_ID": "",
      "H23-SOURCE_SYSTEM": "",
      "H24-ENCRYPT_PASSWORD": "",
      "H25-PDF_TEMPLATE_ID": "",
      "H26-SEND_MAIL_IND": "N",
      "H27-PDF_NAME": "",
      "B01-BUYER_ID": "",
      "B02-BUYER_NAME": invoice.CUSTOMER_FULLNAME,
      "B03-BUYER_TAX_ID_TYPE": "TXID",
      "B04-BUYER_TAX_ID": invoice.BILL_TAX_NO,
      "B05-BUYER_BRANCH_ID": "00000",
      "B06-BUYER_CONTACT_PERSON_NAME": "",
      "B07-BUYER_CONTACT_DEPARTMENT_NAME": "",
      "B08-BUYER_URIID": "",
      "B09-BUYER_CONTACT_PHONE_NO": "",
      "B10-BUYER_POST_CODE": "10250",
      "B11-BUYER_BUILDING_NAME": "",
      "B12-BUYER_BUILDING_NO": "",
      "B13-BUYER_ADDRESS_LINE1": invoice.BILL_ADDRESS,
      "B14-BUYER_ADDRESS_LINE2": "",
      "B15-BUYER_ADDRESS_LINE3": "",
      "B16-BUYER_ADDRESS_LINE4": "",
      "B17-BUYER_ADDRESS_LINE5": "",
      "B18-BUYER_STREET_NAME": "",
      "B19-BUYER_CITY_SUB_DIV_ID": "",
      "B20-BUYER_CITY_SUB_DIV_NAME": "",
      "B21-BUYER_CITY_ID": "",
      "B22-BUYER_CITY_NAME": "",
      "B23-BUYER_COUNTRY_SUB_DIV_ID": "",
      "B24-BUYER_COUNTRY_SUB_DIV_NAME": "",
      "B25-BUYER_COUNTRY_ID": "TH",
      "O01-SHIP_TO_ID": "",
      "O02-SHIP_TO_NAME": "",
      "O03-SHIP_TO_TAX_ID_TYPE": "",
      "O04-SHIP_TO_TAX_ID": "",
      "O05-SHIP_TO_BRANCH_ID": "",
      "O06-SHIP_TO_CONTACT_PERSON_NAME": "",
      "O07-SHIP_TO_CONTACT_DEPARTMENT_NAME": "",
      "O08-SHIP_TO_URIID": "",
      "O09-SHIP_TO_PHONE_NO": "",
      "O10-SHIP_TO_POST_CODE": "",
      "O11-SHIP_TO_BUILDING_NAME": "",
      "O12-SHIP_TO_BUILDING_NO": "",
      "O13-SHIP_TO_ADDRESS_LINE1": "",
      "O14-SHIP_TO_ADDRESS_LINE2": "",
      "O15-SHIP_TO_ADDRESS_LINE3": "",
      "O16-SHIP_TO_ADDRESS_LINE4": "",
      "O17-SHIP_TO_ADDRESS_LINE5": "",
      "O18-SHIP_TO_STREET_NAME": "",
      "O19-SHIP_TO_CITY_SUB_DIV_ID": "",
      "O20-SHIP_TO_CITY_SUB_DIV_NAME": "",
      "O21-SHIP_TO_CITY_ID": "",
      "O22-SHIP_TO_CITY_NAME": "",
      "O23-SHIP_TO_COUNTRY_SUB_DIV_ID": "",
      "O24-SHIP_TO_COUNTRY_SUB_DIV_NAME": "",
      "O25-SHIP_TO_COUNTRY_ID": "",
      "LINE_ITEM_INFORMATION": Array.isArray(invoice.SAL_SALES_INVOICE_ITEM) ? invoice.SAL_SALES_INVOICE_ITEM.map((item, idx) => ({
        "L01-LINE_ID": String(idx + 1),
        "L02-PRODUCT_ID": String(item.PRODUCT_ID),
        "L03-PRODUCT_NAME": String(item.PRODUCT_NAME),
        "L04-PRODUCT_DESC": "",
        "L05-PRODUCT_BATCH_ID": "",
        "L06-PRODUCT_EXPIRE_DTM": "",
        "L07-PRODUCT_CLASS_CODE": "",
        "L08-PRODUCT_CLASS_NAME": "",
        "L09-PRODUCT_ORIGIN_COUNTRY_ID": "",
        "L10-PRODUCT_CHARGE_AMOUNT": String(item.TOTAL_PRICE_FC),
        "L11-PRODUCT_CHARGE_CURRENCY_CODE": "THB",
        "L12-PRODUCT_ALLOWANCE_CHARGE_IND": "true",
        "L13-PRODUCT_ALLOWANCE_ACTUAL_AMOUNT": "",
        "L14-PRODUCT_ALLOWANCE_ACTUAL_CURRENCY_CODE": "THB",
        "L15-PRODUCT_ALLOWANCE_REASON_CODE": "",
        "L16-PRODUCT_ALLOWANCE_REASON": "",
        "L17-PRODUCT_QUANTITY": item.QTY,
        "L18-PRODUCT_UNIT_CODE": "",
        "L19-PRODUCT_QUANTITY_PER_UNIT": "",
        "L20-LINE_TAX_TYPE_CODE": "VAT",
        "L21-LINE_TAX_CAL_RATE": "7.00",
        "L22-LINE_BASIS_AMOUNT": "",
        "L23-LINE_BASIS_CURRENCY_CODE": "",
        "L24-LINE_TAX_CAL_AMOUNT": "",
        "L25-LINE_TAX_CAL_CURRENCY_CODE": "",
        "L26-LINE_ALLOWANCE_CHARGE_IND": "",
        "L27-LINE_ALLOWANCE_ACTUAL_AMOUNT": "",
        "L28-LINE_ALLOWANCE_ACTUAL_CURRENCY_CODE": "",
        "L29-LINE_ALLOWANCE_REASON_CODE": "",
        "L30-LINE_ALLOWANCE_REASON": "",
        "L31-LINE_TAX_TOTAL_AMOUNT": String(item.TOTAL_PRICE_FC),
        "L32-LINE_TAX_TOTAL_CURRENCY_CODE": "",
        "L33-LINE_NET_TOTAL_AMOUNT": String(item.TOTAL_PRICE_FC),
        "L34-LINE_NET_TOTAL_CURRENCY_CODE": "",
        "L35-LINE_NET_INCLUDE_TAX_TOTAL_AMOUNT": String(item.TOTAL_PRICE_FC),
        "L36-LINE_NET_INCLUDE_TAX_TOTAL_CURRENCY_CODE": "",
        "L37-PRODUCT_REMARK1": "",
        "L38-PRODUCT_REMARK2": "",
        "L39-PRODUCT_REMARK3": "",
        "L40-PRODUCT_REMARK4": "",
        "L41-PRODUCT_REMARK5": "",
        "L42-PRODUCT_REMARK6": "",
        "L43-PRODUCT_REMARK7": "",
        "L44-PRODUCT_REMARK8": "",
        "L45-PRODUCT_REMARK9": "",
        "L46-PRODUCT_REMARK10": ""
      })) : [],
      "F01-LINE_TOTAL_COUNT": "10",
      "F02-DELIVERY_OCCUR_DTM": "",
      "F03-INVOICE_CURRENCY_CODE": "",
      "F04-TAX_TYPE_CODE1": "",
      "F05-TAX_CAL_RATE1": "",
      "F06-BASIS_AMOUNT1": "",
      "F07-BASIS_CURRENCY_CODE1": "",
      "F08-TAX_CAL_AMOUNT1": "",
      "F09-TAX_CAL_CURRENCY_CODE1": "",
      "F10-TAX_TYPE_CODE2": "",
      "F11-TAX_CAL_RATE2": "",
      "F12-BASIS_AMOUNT2": "",
      "F13-BASIS_CURRENCY_CODE2": "",
      "F14-TAX_CAL_AMOUNT2": "",
      "F15-TAX_CAL_CURRENCY_CODE2": "",
      "F16-TAX_TYPE_CODE3": "",
      "F17-TAX_CAL_RATE3": "",
      "F18-BASIS_AMOUNT3": "",
      "F19-BASIS_CURRENCY_CODE3": "",
      "F20-TAX_CAL_AMOUNT3": "",
      "F21-TAX_CAL_CURRENCY_CODE3": "",
      "F22-TAX_TYPE_CODE4": "",
      "F23-TAX_CAL_RATE4": "",
      "F24-BASIS_AMOUNT4": "",
      "F25-BASIS_CURRENCY_CODE4": "",
      "F26-TAX_CAL_AMOUNT4": "",
      "F27-TAX_CAL_CURRENCY_CODE4": "",
      "F28-ALLOWANCE_CHARGE_IND": "",
      "F29-ALLOWANCE_ACTUAL_AMOUNT": "",
      "F30-ALLOWANCE_ACTUAL_CURRENCY_CODE": "",
      "F31-ALLOWANCE_REASON_CODE": "",
      "F32-ALLOWANCE_REASON": String(invoice.GRAND_TOTAL_FC),
      "F33-PAYMENT_TYPE_CODE": "THB",
      "F34-PAYMENT_DESCRIPTION": "",
      "F35-PAYMENT_DUE_DTM": "",
      "F36-ORIGINAL_TOTAL_AMOUNT": "",
      "F37-ORIGINAL_TOTAL_CURRENCY_CODE": "",
      "F38-LINE_TOTAL_AMOUNT": "",
      "F39-LINE_TOTAL_CURRENCY_CODE": "",
      "F40-ADJUSTED_INFORMATION_AMOUNT": "",
      "F41-ADJUSTED_INFORMATION_CURRENCY_CODE": "",
      "F42-ALLOWANCE_TOTAL_AMOUNT": "",
      "F43-ALLOWANCE_TOTAL_CURRENCY_CODE": "",
      "F44-CHARGE_TOTAL_AMOUNT": "",
      "F45-CHARGE_TOTAL_CURRENCY_CODE": "",
      "F46-TAX_BASIS_TOTAL_AMOUNT": "",
      "F47-TAX_BASIS_TOTAL_CURRENCY_CODE": "",
      "F48-TAX_TOTAL_AMOUNT": "",
      "F49-TAX_TOTAL_CURRENCY_CODE": "",
      "F50-GRAND_TOTAL_AMOUNT": "1,000.00",
      "F51-GRAND_TOTAL_CURRENCY_CODE": "",
      "F52-TERM_PAYMENT": "",
      "F53-WITHHOLDINGTAX_TYPE1": "",
      "F54-WITHHOLDINGTAX_DESCRIPTION1": "",
      "F55-WITHHOLDINGTAX_RATE1": "",
      "F56-WITHHOLDINGTAX_BASIS_AMOUNT1": "",
      "F57-WITHHOLDINGTAX_TAX_AMOUNT1": "",
      "F58-WITHHOLDINGTAX_TYPE2": "",
      "F59-WITHHOLDINGTAX_DESCRIPTION2": "",
      "F60-WITHHOLDINGTAX_RATE2": "",
      "F61-WITHHOLDINGTAX_BASIS_AMOUNT2": "",
      "F62-WITHHOLDINGTAX_TAX_AMOUNT2": "",
      "F63-WITHHOLDINGTAX_TYPE3": "",
      "F64-WITHHOLDINGTAX_DESCRIPTION3": "",
      "F65-WITHHOLDINGTAX_RATE3": "",
      "F66-WITHHOLDINGTAX_BASIS_AMOUNT3": "",
      "F67-WITHHOLDINGTAX_TAX_AMOUNT3": "",
      "F68-WITHHOLDINGTAX_TOTAL_AMOUNT": "",
      "F69-ACTUAL_PAYMENT_TOTAL_AMOUNT": "",
      "F70-DOCUMENT_REMARK1": "",
      "F71-DOCUMENT_REMARK2": "",
      "F72-DOCUMENT_REMARK3": "",
      "F73-DOCUMENT_REMARK4": "",
      "F74-DOCUMENT_REMARK5": "",
      "F75-DOCUMENT_REMARK6": "",
      "F76-DOCUMENT_REMARK7": "",
      "F77-DOCUMENT_REMARK8": "",
      "F78-DOCUMENT_REMARK9": "",
      "F79-DOCUMENT_REMARK10": "",
      "T01-TOTAL_DOCUMENT_COUNT": "1"
    },   
    PDFContent: ""
  };
};

// ส่งข้อมูลไปยัง e-tax API
exports.submitToEtax = async (payload) => {
  try {
    const response = await axios.post(
      "https://uatservice-etax.one.th/etaxjsonws/etaxsigndocument",
      payload,
      {
        headers: {
          "Content-Type": "application/json",
          "Authorization": process.env.ETAX_AUTH || ""
        }
      }
    );
    return { success: true, data: response.data };
  } catch (error) {
    return { success: false, error: error.response ? error.response.data : error.message };
  }
};
